version: '2.2'
services:

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysqldb01:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mysql-network


networks:
  mysql-network:
    driver: bridge
